name: schema-registry-images
lang: python
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp-dockerfile
  docker_repos: ['confluentinc/cp-schema-registry']
  maven_phase: 'package'
  maven_skip_deploy: true
  build_arm: true
  sign_images: true
  os_types: ['ubi8']
  nano_versions: true
  use_packages: true
  cp_images: true
