name: schema-registry-images
lang: unknown
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp-dockerfile
  docker_repos: ['confluentinc/cp-schema-registry']
  maven_phase: 'package'
  maven_skip_deploy: true
  os_types: ['ubi8']
  nano_versions: true
  build_arm: true
